### ISSUE TITLE
uri vs url

### ISSUE THREAD

**Issue by dlrtn** [dlrtn/web-socket-chat#55]
**URI**
: 특정 리소스를 식별하는 통합 자원 식별자, 웹 기술에서 사용하는 논리적 또는 물리적 리소스를 식별하는 고유한 문자열 시퀀스

**URL**
: 컴퓨터 네트워크 상에서 리소스가 어디 있는지 알려주기 위한 규약, URI의 서브셋

**가장 큰 차이점으로 URI는 식별하고, URL은 위치를 가르킴.**

이름(URI)은 식별자라고 볼수 있지만 위치나 연락처에 대한 정보가 없으므로 URL은 될 수 없음
광주광역시 남구 ~~는 주소로 특정 위치를 가르키므로 URL 및 URI와 비슷하며 간접적으로 내가 있는 장소를 식별

https://www.localhost.com/index.html => index.html
https://www.localhost.com/index => rewrite => index.html
두 주소는 모두 index.html을 가리키고 있음. 첫번째 주소는 웹서버의 실제 파일 위치를 나타내는 주소이므로 URI면서 URL이다.
두 번째 주소는 실제로 index라는 파일이 웹서버에 존재하지 않으므로 URL은 아니다. 하지만 서버 내부에서 이를 rewrite하여 결국 index.html을 가리키기 때문에 URI라고 볼 수 있음.

**URI의 구조**
: 일반 URI는 다음과 같은 형태를 나타냄
`scheme:[//[user[:password]@]host[:port]][/path][?query][#fragment]`

scheme : 사용할 프로토콜을 뜻하며 웹에서는 http 또는 https를 사용
user와 password : (서버에 있는) 데이터에 접근하기 위한 사용자의 이름과 비밀번호
host와 port : 접근할 대상(서버)의 호스트명과 포트번호
path : 접근할 대상(서버)의 경로에 대한 상세 정보
query : 접근할 대상에 전달하는 추가적인 정보 (파라미터)
fragment : 메인 리소스 내에 존재하는 서브 리소스에 접근할 때 이를 식별하기 위한 정보

**Comment by woojae9488** [comment]
@dlrtn 
Spring의 `UriComponentsBuilder`에 대해 추가적으로 정리가 필요해 보입니다.
