### ISSUE TITLE
logback을 이용한 로거 추가

### ISSUE THREAD

**Issue by woojae9488** [dlrtn/web-socket-chat#6]

**Comment by dlrtn** [comment]
LogBack은 Logging Interface인 SLF4J의 Native 구현체입니다.
SLF4J를 사용하여 로깅 처리를 하면 실제 로그는 LogBack에서 출력하게 됩니다.
![image](https://user-images.githubusercontent.com/87226112/160648535-fbe599ec-99de-42f1-bcbe-9961e743c230.png)
![image](https://user-images.githubusercontent.com/87226112/160650966-0c2f6448-7707-416e-a896-8b30c1042e09.png)
의존성은 못 찾았습니다.

일반적인 용례
![image](https://user-images.githubusercontent.com/87226112/160652762-4960029f-2ca5-4d4c-a8ea-f99556bd2310.png)
1. org.slf4j 패키지의 Logger, LoggerFactory Class Import
2. LoggerFactory Class의 getLogger 메소드를 통해 Logger 객체 생성
3. Logger 객체의 로그 레벨명의 메소드를 통해 원하는 레벨의 로그를 출력하도록

그외 설정파일 건드리는 부분
참고 레퍼런스
https://thinkwarelab.wordpress.com/2016/11/18/java%EC%97%90%EC%84%9C-logback%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%A1%9C%EA%B9%85logging-%EC%82%AC%EC%9A%A9%EB%B2%95/

**Comment by woojae9488** [comment]
@dlrtn 
참고 : https://engkimbs.tistory.com/767
위의 링크는 간단히 설명되어 있어서 설정 관련해서 추가적으로 더 알아봐야 합니다.

**Comment by dlrtn** [comment]
LogBack이란 Log4J를 기반으로 개발된 로깅 라이브러리

LogBack 특징
로그에 특정 레벨을 설정할 수 있음
Trace - Debug - Info - Warn - Error
실운영과 테스트 상황에서 각각 다른 출력 레벨을 설정하여 로그를 확인할 수 있음.
출력 방식에 대해 설정할 수 있음
설정 파일을 일정 시간마다 스캔하여 어플리케이션 중단 없이 설정 변경 가능
별도의 프로그램 없이 자체적으로 로그 압축을 지원
로그 보관 기관 설정 가능

LogBack 설정
일반적으로 Classpath에 존재하는 logback 설정 파일 참고
logback-spring.xml 파일을 참조함

appender
Log의 형태 및 어디에 출력할지 설정하기 위한 영역
ConsoleAppender : 콘솔에 출력
FileAppender : 파일에 출력
RollingFileAppender : 여러 개의 파일을 순회하며 저장
SMTPAppender : 로그를 메일로
DBAppender : 데이터베이스에 로그를 저장

encoder
Appender 내에 포함되는 항목으로 pattern을 사용하여 원하는형식으로 로그를 표현할 수 있음

root
설정한 Appender를 참조하여 로그의 레벨을 설정할 수 있음
root는 전역 설정으로, 지역 설정을 하기 위해서는 logger를 사용
