### ISSUE TITLE
spring security 흐름 분석

### ISSUE THREAD

**Issue by woojae9488** [dlrtn/web-socket-chat#7]

**Comment by dlrtn** [comment]
Spring Security를 사용하는 것만으로도 인증과정이 생김..
user / tomcat 실행 시 token으로 로그인

**인증정보를 담고 있는 객체들**
**Principal**

> ```
>  @GetMapping("/user")
>  public String user(Model model, Principal principal) {
>     // Principal을 통해 인증 주체가 누구인지 알 수 있다.
>     model.addAttribute("username", principal.getName());
>     return "/user";
>  }
> ```
> 위처럼 인증을 거치게 될 경우, 인증주체에 대한 정보는 Principal 객체에 저장됨, principal은 스프링 시큐리티가 제공하는 인증정보의 한 부분으로 스프링 시큐리티는 인증에 대한 모든 정보를 아래와 같은 상태로 제공
> ![image](https://user-images.githubusercontent.com/87226112/161091848-8f83b8a1-d430-40c1-835b-a16aa3341869.png)
> 
> **Authentication**
> 실질적으로 인증정보를 담고 있는 객체
> principal
>   내가 누구인지에 대한 정보를 담은 객체
>   로그인 id에 해당하는 값을 담고 있음
> credentials
>   인증자격에 대한 정보를 담은 객체
>   비밀번호와 같은 암호 값을 담고 있음
> authorities
>   현재 유저의 권한 정보를 담은 객체

**SecurityContextHolder**

> 시큐리티가 최종적으로 제공하는 객체
> 인증에 대한 정보는 Authentication 객체에 있음
> 하지만 시큐리티는 최종적으로 SecurityContextHolder를 통해 인증 정보를 제공함
> 
> Thread-local
> SecuritiyContextHolder는 SecurityContext 객체를 Thread-local로 제공, 같은 스레드에서는 매개로 주고받지 않아도 언제든지 인증정보에 대한 접근이 가능
> 즉 같은 스레드에서는 SecurityContextHolder를 통해 어디서든 인증정보에 대한 접근이 가능함

**인증처리 흐름과 구조**

> 1. 인증은 어디서 처리되는가
> 
> >  스프링 시큐리티는 수 많은 클래스 및 인터페이스들로 이루어져 있다. 
> > 이 클래스들은 인증환경을 구성하기 위한 각각의 역할이 있으며 
> > 인증처리 역시 관련 시큐리티 클래스들이 적절하게 호출되어 구현된 것
> 
> AuthenticationManager 인터페이스
> 
> > 인증처리 관련 인터페이스
> > authenticate(Authentication authentication) 메서드를 통해 인증을 구현
> 
> ProviderManager 클래스
> 
> > AuthenticationManager의 구현체
> > 실제 인증을 처리
> 
> 인증처리 흐름
> ProviderManager > authenticate(Authentication)
> 1. 인자로 받은 로그인 정보로 userDetailsService의 User 정보를 가져옴
> 2. 가져온 정보에 대한 유효성 검증(계정잠김, 만료여부 등)
> 3. 이상이 없다면 Authentication 객체로 리턴

2. 인증은 어디서 호출되는 가

> 시큐리티 클래스들을 통해 인증 로직을 구현했다면 이를 적절하게 호출하는 것은 스프링 시큐리티 필터들의 몫
> 
> 인증처리 역시 아래와 같은 관련 필터들이 존재함
> 
> UsernamePasswordAuthenticationFilter 필터
> 
> > 폼 인증을 처리하는 시큐리티 필터
> > 해당 필터에서 AuthenticationManager를 호출
> > 인증 후 받은 Authentication객체를 SecurityContextHolder로 포장한다.
> 
> SecurityContextPersistenceFilter 필터
> 
> > 인증된 SecurityContext를 세션에 캐시하는 필터
> > 1. 인증 전 세션에 인증정보가 있는 지 체크
> > 2. 세션에 정보가 있으면 복구해서 재사용(로그인 유지)
> > 3. 세션에 정보가 없으면 인증을 실행한다.
> 
> 인증 흐름
> 
> > 1. SecurityContextPersistenceFilter에서 로그인이 됐는 지 세션체크 (있으면 세션정보로 로그인처리)
> > 2. [1]이 없는 경우 UsernamePasswordAuthenticationFilter로 폼인증 시작 (AuthenticationManager) 호출
> > 3. ProviderManager(&AuthenticationManager)를 통해 인증처리
> > 4. UsernamePasswordAuthenticationFilter를 통해 SecurityContextHolder 객체로 리턴
> > 5. SecurityContextPersistenceFilter를 통해 인증정보를 세션에 담는다.
> 

3. 인가처리

> 인가처리 역시 필터가 관련 기능을 호출하여 구현
> 
> FilterSecurityInterceptor 필터
> 
> > 시큐리티의 필터 중 가장 마지막에 호출되는 필터
> > AccessDecisionManager를 통해 인가 혹은 예외를 던진다.
> 
> AccessDecisionManager 인터페이스
> 
> > 인가 처리 관련 인터페이스
> > 인가 결정을 내리는 인터페이스로 3가지 구현체를 제공
> > - Voter : 의사결정을 내리는데 사용되는 수단
> > 1. AffirmativeBased
> > > - 여러 Voter중에 하나라도 충족하면 허용
> > > - 기본전략
> > 2. ConsensusBased : 다수결
> > 3. UnanimousBased : 만장일치
> > - decide() 메서드를 통해 인가로직 구현
> > - supports(ConfigAttribute attribute)
> > > - hasRole(), permitAll()과 같은 설정을 확인하는 메서드

**스프링 시큐리티 필터**

> 스프링 시큐리티의 인증/인가 환경은 시큐리티의 다양한 필터들이 동작하며 이루어낸 결과다.
> 시큐리티 환경을 커스텀하는 방법도 결국은 이 필터들을 커스텀하거나, 새로운 필터를 직접 구현해야한다.
> 
> 그렇다면 이 필터들은 어떻게 호출되는 것일까?
> 
> ![image](https://user-images.githubusercontent.com/87226112/161094117-15c30665-5549-4e04-84c0-145d52e44fd2.png)
> 필터 흐름에 따라 처리하므로 잘 확인
> 
> DelegatingFilterProxy
> 
> > 클라이언트의 요청을 가로채서 FilterChainProxy에 위임
> > 스프링 부트에서는 관련부분이 자동설정 됨
> 
> FilterChainProxy
> 
> > 필터들의 모음인 FilterChain을 가져온다.
> > (SecurityConfig 설정대로 필터를 가져온다.)

구조
![image](https://user-images.githubusercontent.com/87226112/161094443-32bcda80-eddf-4328-89ca-a03ac943b95d.png)

- UserDetailsService
- - 실제 DB에서 사용자 인증정보를 가져오는 역할을 한다.
- UserDetails
- - UserDeatils객체를 통해 권한 정보를 관리하기 때문에 UserDetails를 구현한 구현체가 반드시 필요하다
- - - CustomUserDetails를 만들고 Mebmer에 리턴해주는 방식을 채택하였다.
- - 넘겨받은 정보를 통해 DB에서 찾은 사용자 정보
- - UserDetails는 인증용객체(Member)와 도메인용 객체(CustomUserDetails)를 분리하지 않고 인증용 객체에서 상속해서 사용하기도 한다.
- - - GrantedAuthority
- 동작 플로우
- - Http Request : 사용자가 로그인 정보와 함께 인증을 요청한다.
- - AuthenticationFilter가 요청을 가로 챈다. 가로친 정보를 바탕으로 UsernamePasswordAuthenticationToken 객체를 생성한다.
- - AuthenticationFilter가 AuthenticationManger의 구현체인 ProviderManager에게 토큰 (UsernamePasswordAuthenticationToken)을 전달한다.
- - 다시 AuthenticationProvider에 UsernamePasswordAuthenticationToken 객체를 전달합니다.
- - AuthenticationProvider가 실제 데이터베이스에서 사용자 인증정보를 가져오는 UserDetailsService에 사용자 정보(아이디)를 넘겨줍니다.
- - 넘겨받은 사용자 정보를 통해 DB에서 찾은 사용자 정보인 UserDetails 객체를 만듭니다.
- - AuthenticationProvider(인증 제공자) 는 UserDetails를 넘겨받고 사용자 정보를 비교합니다.
- - 인증이 완료되면 권한 등의 사용자 정보를 담은 Authentication 객체를 반환합니다. (인증 제공자 -> 인증 관리자)
- - AuthenticationFilter에 Authentication 객체가 반환됩니다.
- - Authentication 객체를 SecurityContext에 저장합니다.


출처:  [[SeongbinDB]](https://seongbindb.tistory.com/169)

참고레퍼런스
https://velog.io/@franc/%EC%8A%A4%ED%94%84%EB%A7%81-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0-%ED%9D%90%EB%A6%84%EA%B3%BC-%EA%B5%AC%EC%A1%B0
