### ISSUE TITLE
swagger 관련 어노테이션 및 설정 정리

### ISSUE THREAD

**Issue by woojae9488** [dlrtn/web-socket-chat#8]

**Comment by dlrtn** [comment]
**1. Swagger란?**

> 서버로 요청되는 URL 리스트를 HTML화면으로 문서화 및 테스트 할 수 있는 라이브러리
> Open Api Specification(OAS)를 위한 프레임워크로 REST API 스펙 명세 및 관리가 목적
> 
> 간단하게 서버에 있는 REST API 들을 HTML 화면으로 노출해주는 툴이라고 생각하면 된다. 하드코딩으로 API들을 명시해주는게 아니고 서버에 있는 API들을 바로 노출해주기 때문에 동기화에 대한 걱정을 하지 않아도 되고 API 가 추가되더라도 문서를 수정하지 않아도 된다.

**2. Springdoc vs Springfox**
![image](https://user-images.githubusercontent.com/87226112/161064329-d1ec87a2-cb1d-4213-9162-3b54afde28ef.png)

> fox가 선발주자, doc이 후발주자로 업데이트같은 자잘한 내용 제외하고 참고한 레퍼런스에서는 Springdoc이 API별로 그룹핑을 지원해주기 때문에 사용한다고 한다

++ 의존성 추가는 springdoc만 해도 swaager-ui, webjars-locator-core 등이 추가됨

핵심 로직 = swagger - ui
핵심 로직 활용 = springdoc-openapi

**3. Spring Boot에 Swagger 적용**
1. 의존성추가
2. SwaggerConfig로 swagger configuration 관리 => config/swagger dir

```
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import lombok.RequiredArgsConstructor;
import org.springdoc.core.GroupedOpenApi;
import org.springdoc.core.customizers.OpenApiCustomiser;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@OpenAPIDefinition(
        info = @Info(title = "API 명세서",
                description = "API 명세서 테스트 입니다.",
                version = "v1"))
@Configuration
@RequiredArgsConstructor
public class SwaggerConfig {

    @Bean
    public GroupedOpenApi customTestOpenAPi() {
    	// /test 로 시작하는 API 들을 테스트 관련 API 로 그룹핑 
    	// member 로 시작하는 API 를 그룹핑 하고 싶다 라고 하면 메소드 이름을 변경하고 하나 더 만들어서 설정하면 됨 
   		
        String[] paths = {"/test/**"};
        
        return GroupedOpenApi
                .builder()
                .group("테스트 관련 API")
                .pathsToMatch(paths)
                .addOpenApiCustomiser(buildSecurityOpenApi()).build();
    }

    public OpenApiCustomiser buildSecurityOpenApi() {
    	// jwt token 을 한번 설정하면 header 에 값을 넣어주는 코드, 자세한건 아래에 추가적으로 설명할 예정 
       
        return OpenApi -> OpenApi.addSecurityItem(new SecurityRequirement().addList("jwt token"))
                .getComponents().addSecuritySchemes("jwt token", new SecurityScheme()
                        .name("Authorization")
                        .type(SecurityScheme.Type.HTTP)
                        .in(SecurityScheme.In.HEADER)
                        .bearerFormat("JWT")
                        .scheme("bearer"));
    }

}
```

3. 테스트 api 추가
@Operation | 해당 API 에 대한 정보
@ApiReposnses | response 에 대한 정보로 여러개의 @ApiResponse 를 가지고 있다
@ApiResponse | response 코드와 설명을 설정
@Parameter | 파라미터에 대한 정보

화면적용 예시
![image](https://user-images.githubusercontent.com/87226112/161072591-1e4d38a9-0c6e-49cc-9d10-6bcf4e275745.png)

상기코드 참고
1 ➡️ swagger 문서에 대한 간략한 설명
@OpenAPIDefinition

2 ➡️ 실제 API 호출
![image](https://user-images.githubusercontent.com/87226112/161072961-0dd8fb23-5113-4420-b80b-97298d00a9aa.png)

API 를 실제로 호출하고 싶다면 파라미터에 원하는 값을 넣어주고 Try it out 을 실행하면 된다.

3 ➡️ API 별 그룹핑
![image](https://user-images.githubusercontent.com/87226112/161073040-ff4c8647-2cd5-4de3-a95d-1973a975e87c.png)
그룹핑이 여러개 있는 경우 select 박스이기 때문에 다른 그룹을 선택해 확인할 수 있다.

4 ➡️ JWT token 설정
![image](https://user-images.githubusercontent.com/87226112/161072719-0a95af8f-815b-41cb-bda7-9e1be6efe87d.png)
buildSecurityOpenApi 메소드를 만들어주고 addOpenApiCustomiser를 넣어주면 해당 그룹에 jwt token을 넣을 수 있다.

참고한 레퍼런스
https://velog.io/@soyeon207/%EC%9A%B0%EB%8B%B9%ED%83%95%ED%83%95-Swagger-%EC%A0%81%EC%9A%A9%EA%B8%B0
https://tecoble.techcourse.co.kr/post/2020-08-31-spring-swagger/
